### ISSUE TITLE
User can currently pay and question the title claim—can these two options coexist, or must the user choose one?

### ISSUE THREAD

**Issue by beilert00** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#31]
On the form, the user can check both that they agree to pay and can also question the title claim. Is there some kind of escrow or avenue where both are possible, or should we offer these as two different options, one of which the user must choose?

**Comment by beilert00** [comment]
ANSWER FROM 6/25/24 MEETING W/ TRIAL CT LEADERSHIP: These two options can coexist, so we must approach this question in a way that allows the user to select both options.

**Comment by KarlaRFuentes** [comment]
Our current form has been formatted to allow the user to pick both options if necessary.
