### ISSUE TITLE
Ask for the answer due date and advise if the answer is late; include information in interview metadata

### ISSUE THREAD

**Issue by beilert00** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#32]
There seems to be a date loophole in our project, if there is a “return answer by” date in the document, shouldn’t the interview kick them out if they are past the return answer date?

**Comment by KarlaRFuentes** [comment]
Date comes from the citation according to the current Guide and File interview. The current interview does not ask about their return by date.

**Comment by beilert00** [comment]
ANSWER FROM 6/25/24 MEETING W/ TRIAL CT LEADERSHIP: Not an issue, as flexibility (motion to late answer, etc.) is common in this specific field of law.

1. In the complaint, based on file date when that gets initiated, Court leadership will double check. 30 or 60 days to answer by defendant, they just put it in as informational. As far as getting it on the form, not necessary. Date is when you need to file the answer by. For this tax lien type thing, tehy will file a motion to file a late answer. 
In the interview metadata, on the top of the file, there are two sections:

2. If not, look for a motion to late answer.

3. At some point, we’ll probably ask for the code its tied to to e-file. In addition to that code, we have some others that are related to what we are discussing. Is this late? If so, what triggers use of one code over another. Probably a 1 to 1 code form.

**Comment by samglover** [comment]
I think @colarusso suggested asking for the answer due date and letting them know what they will need to do if the date has passed (file a motion for late answer along with it). And at some point we can probably include that in this interview.

We should also mention the need to get the answer deadline from the complaint in the interview metadata (can_I_use_this_form and before_you_start).

**Comment by KarlaRFuentes** [comment]
For now the decision-makers would just like us to advise the user at the beginning of the interview that if they are passed their answer by date that they must request and extension. We are having an issue finding a page to link explaining the steps or even finding the form so we are going to reach out to the decision- makers.
