### ISSUE TITLE
User's contact information is not required, yet address information is. Possible future communication issue with user and others due to this?

### ISSUE THREAD

**Issue by beilert00** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#33]
User’s address information is required, yet contact information is not. Is this okay, or does it pose a possible communication issue with the court and the user? Currently, the address information would provide the court or other parties the user's address information, yet there would be no required contact information to reach the user if the user does not wish to provide it.

**Comment by beilert00** [comment]
ANSWER FROM 6/25/24 MEETING W/ TRIAL CT LEADERSHIP: Require contact information like we do with address information.

**Comment by KarlaRFuentes** [comment]
For this part of the form I created a validation code which requires the user to give at least one phone number before they can move on to a different question. A warning pops up for them explaining this requirement.
