### ISSUE TITLE
Can we confirm the documentation the user receives informing them of their tax lien?

### ISSUE THREAD

**Issue by KarlaRFuentes** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#39]
I was able to find a pdf of the complaint but not the citation. Can we get access to a pdf of the citation?

**Comment by beilert00** [comment]
FROM COURT LEADERSHIP: Citation and answer will both be sent our way so we can get access to all pertinent information.

**Comment by KarlaRFuentes** [comment]
Citation and Complaint sample packet was sent by court leadership on 7/10/2024.
