### ISSUE TITLE
How do we label the defendant?

### ISSUE THREAD

**Issue by beilert00** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#46]
ANSWER FROM CT LEADERSHIP MEETING 7/24: 

Pro se: "Self-representing defendant." The court cares about this distinguishment.
       - "Are you represented by a lawyer?"
              - "No, I am representing myself."
              - "Yes, I am represented by..."

"In a couple of places: 'person who is named in a tax lien case.'"

“Is anyone else on your side of this case?”
       - “Are there any other defendants named in the tax lien complaint?”

Capitalize Plaintiff and Defendant.

**Comment by KarlaRFuentes** [comment]
Defendant will be referred to as Self-representing defendant and will be defined as "the person who has been sued because of a tax lien on their property."
