### ISSUE TITLE
Issue with preview of form page when it displays. 

### ISSUE THREAD

**Issue by KarlaRFuentes** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#51]
The page with the Id: Preview_of_taxlien_answer needs to be fixed in the following ways:
1. The preview photos of the form show up very small for the interview users. 
2. There is not an option to enlarge the photos.

**Comment by taylorkoch** [comment]
Added a link to the full version of the pdf as suggested by the Trial Court. Got their approval on this change.
