### ISSUE TITLE
Update Next Steps Document

### ISSUE THREAD

**Issue by KarlaRFuentes** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#55]
The next steps need to include the following: 

      When you are finished, you will need to:
  
         * Serve this Tax Lien Answer by delivering or mailing a copy to the Plaintiff or their attorney.
          * File this Tax Lien Answer by delivering, mailing, or electronically filing a copy to/with the Land Court.

There are also some sections that are in the next steps which do not apply to this form and they need to be taken out.

**Comment by taylorkoch** [comment]
If the completed forms are meant to have e-filing enabled, now or in the future, the instructions in the next-steps document should take that into account.

Here are two examples from existing interviews:

[209A Domestic Violence Restraining Order](https://github.com/SuffolkLITLab/docassemble-MA209AProtectiveOrder/blob/master/docassemble/MA209AProtectiveOrder/data/templates/209A_next_steps_for_user.docx)
[Petition to Change the Name of a Minor](https://github.com/SuffolkLITLab/docassemble-PetitionToChangeNameMinorCJP25/blob/main/docassemble/PetitionToChangeNameMinorCJP25/data/templates/petition_to_name_change_minor_CJP25_next_steps.docx)

**Comment by taylorkoch** [comment]
updated next steps document with information from Land Court website and fixed issue where template was switching parties
