### ISSUE TITLE
Clean up templates folder

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#66]
It looks like there are two PDF templates in the [**templates** folder](https://github.com/SuffolkLITLab/docassemble-MATCTaxLienAnswer/tree/main/docassemble/MATCTaxLienAnswer/data/templates):

* Tax-Lien-_Form.pdf
* taxlien_answer.pdf

I suspect the first one is not the actual template (or at least the name doesn't conform to the documentation. Let's remove the one we're not using.

**Comment by taylorkoch** [comment]
I tried both and Tax-Lien-_Form was the one that was required for the form to work, so removed taxlien_answer
